"""initial schema

Revision ID: 0bd42c15e942
Revises: 
Create Date: 2026-04-30 19:25:52.080881
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0bd42c15e942'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column(
        'status',
        sa.Enum(
            'CREATED',
            'RUNNING',
            'PARTIAL',
            'COMPLETED',
            'FAILED',
            name='auditstatus',
            native_enum=False,
        ),
        nullable=False,
    ),
    sa.Column('providers', sa.JSON(), nullable=False),
    sa.Column('runs_per_query', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('max_queries', sa.Integer(), nullable=True),
    sa.Column('enable_query_expansion', sa.Boolean(), nullable=False),
    sa.Column('enable_source_intelligence', sa.Boolean(), nullable=False),
    sa.Column('follow_up_depth', sa.Integer(), nullable=False),
    sa.Column(
        'scdl_level',
        sa.Enum('L1', 'L2', name='scdllevel', native_enum=False),
        nullable=False,
    ),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('follow_up_depth IN (0, 1)'),
    sa.CheckConstraint('runs_per_query >= 1 AND runs_per_query <= 5'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column(
        'status',
        sa.Enum(
            'PENDING',
            'RUNNING',
            'COMPLETED',
            'FAILED',
            name='jobstatus',
            native_enum=False,
        ),
        nullable=False,
    ),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('run_number >= 1'),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_jobs_idempotency_key')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column(
        'status',
        sa.Enum(
            'PENDING',
            'SUCCESS',
            'ERROR',
            'TIMEOUT',
            'RATE_LIMITED',
            name='runstatus',
            native_enum=False,
        ),
        nullable=False,
    ),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('run_number >= 1'),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        'audit_id',
        'query_id',
        'provider',
        'run_number',
        name='uq_runs_execution_identity',
    )
    )
    op.create_table('parsed_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('visible_brand', sa.Boolean(), nullable=False),
    sa.Column('brand_position_rank', sa.Integer(), nullable=True),
    sa.Column('prominence_score', sa.Float(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('recommendation_score', sa.Float(), nullable=False),
    sa.Column('source_quality_score', sa.Float(), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('parsed_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('raw_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('request_snapshot', sa.JSON(), nullable=True),
    sa.Column('raw_answer', sa.Text(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('provider_status', sa.String(length=32), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('error_object', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('visibility_score', sa.Float(), nullable=False),
    sa.Column('prominence_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('recommendation_score', sa.Float(), nullable=False),
    sa.Column('source_quality_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('raw_responses')
    op.drop_table('parsed_results')
    op.drop_table('runs')
    op.drop_table('jobs')
    op.drop_table('queries')
    op.drop_table('audits')
    op.drop_table('users')
    op.drop_table('brands')
    # ### end Alembic commands ###
